# Generated by Django 5.2.10 on 2026-01-12 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('default_base_url', models.URLField(blank=True, null=True)),
                ('api_format', models.CharField(choices=[('openai', 'OpenAI Compatible'), ('anthropic', 'Anthropic'), ('google', 'Google Generative AI')], default='openai', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_providers',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='apikey',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='llm.llmprovider'),
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm.llmprovider')),
            ],
            options={
                'db_table': 'llm_models',
                'ordering': ['provider', 'sort_order', 'model_id'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
