# Generated by Django 5.2.10 on 2026-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_add_provider_and_model_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='context_length',
            field=models.IntegerField(blank=True, help_text='Maximum context length in tokens', null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='input_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Input price per million tokens (USD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='output_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Output price per million tokens (USD)', max_digits=10, null=True),
        ),
    ]
